### ISSUE TITLE
Missing release versions

### ISSUE THREAD

**Issue by fredrikekre** [SaschaMann/versions.json-testing#3]
Windows archives (.zip) and musl versions are not included.

OT: Is the `stable` part needed? I note that it was taken from the Go example, but you can infer it from the version string, so what is it useful for? If that is removed we can move up the `files` vector one level. But perhaps it is nice to keep as is if we want to add more keys to the versions later?

**Comment by SaschaMann** [comment]
> I note that it was taken from the Go example, but you can infer it from the version string, so what is it useful for?

True, it's not particularly useful. It could potentially save some minor work in the consuming code because the version doesn't have to be parsed to determine if it's stable or not. But that's probably a bit of a constructed use-case.

I don't mind having it, nor removing it. @staticfloat do you have any preference?

> But perhaps it is nice to keep as is if we want to add more keys to the versions later?

Some people in https://github.com/JuliaLang/julia/issues/33817 and some other places where this has been discussed before brought up that it might be nice to mark lts releases in the file somehow, so it's probably nice to keep just in case.

**Comment by SaschaMann** [comment]
> Windows archives (.zip) and musl versions are not included.

Fixed in c442b89c954477ea423ebf09f279b763cbdf69e4 and 1161ecd6a4d46251fd6d0dd356d0c4080dc20e57

**Comment by fredrikekre** [comment]
> Some people in JuliaLang/julia#33817 and some other places where this has been discussed before brought up that it might be nice to mark lts releases in the file somehow, so it's probably nice to keep just in case.

Yea, but is this the file to store that info in? I think it is nice that this json file is pretty static like it is now. Perhaps we can have a separate file for "current" information like LTS, current stable release, current beta release etc. Basically a JSON of this page https://julialang.org/downloads/

**Comment by staticfloat** [comment]
I think the .json changing once every couple of months is static enough.  :P
