### ISSUE TITLE
Feature request: list `1.6-nightly` in the `versions.json` file

### ISSUE THREAD

**Issue by DilumAluthge** [SaschaMann/versions.json-testing#7]
Available for download e.g. here: https://julialangnightlies-s3.julialang.org/bin/linux/x64/1.6/julia-latest-linux64.tar.gz

`1.X-nightly` is only available during the period of time after `release-1.X` has been branched and before `1.X.0` has been released.

**Comment by SaschaMann** [comment]
Could you outline a use case where this would be helpful to have?

Normal nightlies aren't listed in the file (see https://github.com/JuliaLang/julia/issues/33817) because they change too often, these would have the same issue(s).

Rebuilding it is quite expensive (~30 min) so even if we rebuilt it frequently, the info and hashes would likely be out of date a lot of the time, leading to issues in the tools.

**Comment by DilumAluthge** [comment]
Ohh, I didn't realize that the normal nightlies aren't listed in `versions.json`.
